deeptools/HiCExplorer

- hicexplorer/trackPlot.py
The method to compute the layout was simplified, although now is computed each time an interval wans to be plotted because the layout depends on the fontsize, on the figure width and on the length (in bp) of the region being plotted.
> changed the way in which bed intervals are plotted. 

- hicexplorer/HiCMatrix.py
> pandas import should give no error

- hicexplorer/HiCMatrix.py
- hicexplorer/hicExport.py
Default format was hicexplorer while HiCMatrix accepted npz.. fixed
create dir while writing lieberman simplified
> resolved problem with hicexport

- .gitignore
- docs/content/HiC_export.rst
- docs/content/example_usage.rst
- hicexplorer/HiCMatrix.py
- hicexplorer/hicExport.py
HiCExport can output bioconductor's GInteraction format now..
> Hic export : added new format

- galaxy/wrapper/.shed.yml
- galaxy/wrapper/hicBuildMatrix.xml
- galaxy/wrapper/hicCorrectMatrix.xml
- galaxy/wrapper/hicCorrelate.xml
- galaxy/wrapper/hicFindTADs.xml
- galaxy/wrapper/hicPlotDistVsCounts.xml
- galaxy/wrapper/hicPlotMatrix.xml
- galaxy/wrapper/hicPlotTADs.xml
- galaxy/wrapper/hicSumMatrices.xml
- galaxy/wrapper/macros.xml
I have real problems with creating test data that I can submit to github. I have some locally and the all tests are passing. This does not mean that these tools are on-par with the deeptools onces, I still have much todo but this should work.
> Galaxy updates

- bin/hicMergeTADbins
- hicexplorer/hicCorrectMatrix.py
- hicexplorer/hicFindTADs.py
- hicexplorer/hicMergeMatrixBins.py
- hicexplorer/hicMergeTADbins.py
- hicexplorer/hicPlotMatrix.py
- hicexplorer/reduceMatrix.py
This code creates a new program that, based on a bed file containing domains, creates a new matrix in which the bins of the tads are merged into one.
> Merge tad bins

- galaxy/wrapper/hicBuildMatrix.xml
- galaxy/wrapper/hicPlotMatrix.xml
- galaxy/wrapper/hicPlotTADs.xml
- galaxy/wrapper/macros.xml
- galaxy/wrapper/test-data/Li_et_al_2015.h5
- galaxy/wrapper/test-data/dm3_genes.bed.gz
- galaxy/wrapper/test-data/dm3_genes.bed6.gz
- galaxy/wrapper/test-data/domains.bed
- galaxy/wrapper/test-data/hicBuildMatrix_result1.h5
- galaxy/wrapper/test-data/hicPlotMatrix_result1.svg
- galaxy/wrapper/test-data/hicPlotTADs_result1.svg
- galaxy/wrapper/test-data/small_test_R1_unsorted.bam
- galaxy/wrapper/test-data/small_test_R2_unsorted.bam
- galaxy/wrapper/test-data/tad_classification.bed
- galaxy/wrapper/test-data/tad_score.gz
* update to latest version
* much better test coverage
* cleanups
> Galaxy wrapper updates

- hicexplorer/reduceMatrix.py
Added further test to check that it is working properly.
> code cleanup. Non-symmetric matrices can now be also reduced.

- Makefile
- dev-requirements.txt
- requirements.txt
This PR will add a Makefile which will compile the docs and make a pypi release automatically.
ping @fidelram @joachimwolff
> Release docs

- hicexplorer/findRestSite.py
Unfortunately I cannot reopen a pull request that was already merged, so I had to create a new one.
The fix was also tested in Python 2.
> Fix findRestSite doctests in Python 3

- hicexplorer/hicAggregateContacts.py
- hicexplorer/hicBuildMatrix.py
- hicexplorer/hicCompareMatrices.py
- hicexplorer/hicCorrelate.py
- hicexplorer/hicExport.py
- hicexplorer/hicPlotViewpoint.py
- hicexplorer/hicPrepareQCreport.py
- hicexplorer/hicSumMatrices.py
- hicexplorer/hicTransform.py
> Arguments categorisation for each tool

- setup.py
> install hicAggregateContacts

- .travis.yml
> Travis osx test

- hicexplorer/HiCMatrix.py
- hicexplorer/hicAggregateContacts.py
- hicexplorer/hicPlotMatrix.py
- hicexplorer/test/test_hicmatrix.py
- hicexplorer/utilities.py
the function `toString`  used to convert from bytes to string didn't work with numpy arrays which some times were passed to the function.
> Fix to string

- hicexplorer/hicBuildMatrix.py
> improved description of dangling ends in help message

- hicexplorer/hicBuildMatrix.py
> removed non ascii character

- hicexplorer/utilities.py
> python3 version

- bin/hicAdjustMatrix
- hicexplorer/hicAdjustMatrix.py
- hicexplorer/hicPlotMatrix.py
- setup.py
Replacement script for a part of the old hicExport script.
> Adjust matrix

- hicexplorer/hicAggregateContacts.py
> Linting of hicAggregateContacts

- hicexplorer/__init__.py
- hicexplorer/hicCorrectMatrix.py
- Changing KR correction API call
> Kr references

- .travis.yml
- hicexplorer/_version.py
- requirements.txt
- setup.py
> fixing conda version to 4.6

- .travis.yml
> Remove conda 4.6 clipping

- docs/content/tools/hicCompartmentsPolarization.rst
- hicexplorer/hicAdjustMatrix.py
- hicexplorer/hicCompartmentsPolarization.py
* modified the line length for the bed file which provided as a list of regions
> Fix hic adjust

- hicexplorer/hicDetectLoops.py
- hicexplorer/hicPlotMatrix.py
> Loop fixes

- hicexplorer/hicCompartmentalization.py
> Compartmentalization bugfix

- hicexplorer/__init__.py
- hicexplorer/_version.py
- hicexplorer/chicViewpoint.py
> Chic bugfix

- hicexplorer/_version.py
- hicexplorer/hicPlotMatrix.py
> Adding the option to rotate x and y labels and to adjust the font size

- hicexplorer/hicMergeDomains.py
- setup.py
> final version

- docs/content/tools/hicPlotTADs.rst
> Update the url for pgt doc

- requirements.txt
- setup.py
added ipykernel to the dependencies
> added ipykernel to the dependencies

- hicexplorer/hicBuildMatrix.py
- hicexplorer/hicPlotMatrix.py
> WIP - working on the bug reported in #596

- hicexplorer/hicAggregateContacts.py
- hicexplorer/hicAverageRegions.py
Merging feature that I forgot to merge for 3.7 version.
> Aggregate average strand information

- .github/ISSUE_TEMPLATE.md
This would avoid unanswered issues while I could answer on pGT.
> Update ISSUE_TEMPLATE.md to suggest pgt

- docs/content/News.rst
- hicexplorer/_version.py
I wait for the CI to do this job:
> Fix version

- docs/content/News.rst
- hicexplorer/_version.py
- hicexplorer/test/general/test_chicAggregateStatistic.py
> Release 3.7.5
